/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/
#include "stdafx.h"
#include <string.h>
#include "ckLcmType_velodynegrid_t.h"

static int __ckLcmType_velodynegrid_t_hash_computed;
static int64_t __ckLcmType_velodynegrid_t_hash;

int64_t __ckLcmType_velodynegrid_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ckLcmType_velodynegrid_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__ckLcmType_velodynegrid_t_get_hash;
    (void) cp;

    int64_t hash = (int64_t)0x5ef6d3fbea992b8bLL
         + __int64_t_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ckLcmType_velodynegrid_t_get_hash(void)
{
    if (!__ckLcmType_velodynegrid_t_hash_computed) {
        __ckLcmType_velodynegrid_t_hash = __ckLcmType_velodynegrid_t_hash_recursive(NULL);
        __ckLcmType_velodynegrid_t_hash_computed = 1;
    }

    return __ckLcmType_velodynegrid_t_hash;
}

int __ckLcmType_velodynegrid_t_encode_array(void *buf, int offset, int maxlen, const ckLcmType_velodynegrid_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].position, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].orientation, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].velocity, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].wid_step), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].height_step), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].grid_nums), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, p[element].velo_grid, p[element].grid_nums);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].enabled), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ckLcmType_velodynegrid_t_encode(void *buf, int offset, int maxlen, const ckLcmType_velodynegrid_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __ckLcmType_velodynegrid_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ckLcmType_velodynegrid_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __ckLcmType_velodynegrid_t_encoded_array_size(const ckLcmType_velodynegrid_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].timestamp), 1);

        size += __double_encoded_array_size(p[element].position, 3);

        size += __double_encoded_array_size(p[element].orientation, 3);

        size += __double_encoded_array_size(p[element].velocity, 3);

        size += __int32_t_encoded_array_size(&(p[element].width), 1);

        size += __int32_t_encoded_array_size(&(p[element].height), 1);

        size += __float_encoded_array_size(&(p[element].wid_step), 1);

        size += __float_encoded_array_size(&(p[element].height_step), 1);

        size += __int32_t_encoded_array_size(&(p[element].grid_nums), 1);

        size += __int8_t_encoded_array_size(p[element].velo_grid, p[element].grid_nums);

        size += __boolean_encoded_array_size(&(p[element].enabled), 1);

    }
    return size;
}

int ckLcmType_velodynegrid_t_encoded_size(const ckLcmType_velodynegrid_t *p)
{
    return 8 + __ckLcmType_velodynegrid_t_encoded_array_size(p, 1);
}

int __ckLcmType_velodynegrid_t_decode_array(const void *buf, int offset, int maxlen, ckLcmType_velodynegrid_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].position, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].orientation, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].velocity, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].wid_step), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].height_step), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].grid_nums), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].velo_grid = (int8_t*) lcm_malloc(sizeof(int8_t) * p[element].grid_nums);
        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, p[element].velo_grid, p[element].grid_nums);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].enabled), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ckLcmType_velodynegrid_t_decode_array_cleanup(ckLcmType_velodynegrid_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].timestamp), 1);

        __double_decode_array_cleanup(p[element].position, 3);

        __double_decode_array_cleanup(p[element].orientation, 3);

        __double_decode_array_cleanup(p[element].velocity, 3);

        __int32_t_decode_array_cleanup(&(p[element].width), 1);

        __int32_t_decode_array_cleanup(&(p[element].height), 1);

        __float_decode_array_cleanup(&(p[element].wid_step), 1);

        __float_decode_array_cleanup(&(p[element].height_step), 1);

        __int32_t_decode_array_cleanup(&(p[element].grid_nums), 1);

        __int8_t_decode_array_cleanup(p[element].velo_grid, p[element].grid_nums);
        if (p[element].velo_grid) free(p[element].velo_grid);

        __boolean_decode_array_cleanup(&(p[element].enabled), 1);

    }
    return 0;
}

int ckLcmType_velodynegrid_t_decode(const void *buf, int offset, int maxlen, ckLcmType_velodynegrid_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __ckLcmType_velodynegrid_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ckLcmType_velodynegrid_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ckLcmType_velodynegrid_t_decode_cleanup(ckLcmType_velodynegrid_t *p)
{
    return __ckLcmType_velodynegrid_t_decode_array_cleanup(p, 1);
}

int __ckLcmType_velodynegrid_t_clone_array(const ckLcmType_velodynegrid_t *p, ckLcmType_velodynegrid_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __double_clone_array(p[element].position, q[element].position, 3);

        __double_clone_array(p[element].orientation, q[element].orientation, 3);

        __double_clone_array(p[element].velocity, q[element].velocity, 3);

        __int32_t_clone_array(&(p[element].width), &(q[element].width), 1);

        __int32_t_clone_array(&(p[element].height), &(q[element].height), 1);

        __float_clone_array(&(p[element].wid_step), &(q[element].wid_step), 1);

        __float_clone_array(&(p[element].height_step), &(q[element].height_step), 1);

        __int32_t_clone_array(&(p[element].grid_nums), &(q[element].grid_nums), 1);

        q[element].velo_grid = (int8_t*) lcm_malloc(sizeof(int8_t) * q[element].grid_nums);
        __int8_t_clone_array(p[element].velo_grid, q[element].velo_grid, p[element].grid_nums);

        __boolean_clone_array(&(p[element].enabled), &(q[element].enabled), 1);

    }
    return 0;
}

ckLcmType_velodynegrid_t *ckLcmType_velodynegrid_t_copy(const ckLcmType_velodynegrid_t *p)
{
    ckLcmType_velodynegrid_t *q = (ckLcmType_velodynegrid_t*) malloc(sizeof(ckLcmType_velodynegrid_t));
    __ckLcmType_velodynegrid_t_clone_array(p, q, 1);
    return q;
}

void ckLcmType_velodynegrid_t_destroy(ckLcmType_velodynegrid_t *p)
{
    __ckLcmType_velodynegrid_t_decode_array_cleanup(p, 1);
    free(p);
}

int ckLcmType_velodynegrid_t_publish(lcm_t *lc, const char *channel, const ckLcmType_velodynegrid_t *p)
{
      int max_data_size = ckLcmType_velodynegrid_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ckLcmType_velodynegrid_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _ckLcmType_velodynegrid_t_subscription_t {
    ckLcmType_velodynegrid_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void ckLcmType_velodynegrid_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    ckLcmType_velodynegrid_t p;
    memset(&p, 0, sizeof(ckLcmType_velodynegrid_t));
    status = ckLcmType_velodynegrid_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding ckLcmType_velodynegrid_t!!!\n", status);
        return;
    }

    ckLcmType_velodynegrid_t_subscription_t *h = (ckLcmType_velodynegrid_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ckLcmType_velodynegrid_t_decode_cleanup (&p);
}

ckLcmType_velodynegrid_t_subscription_t* ckLcmType_velodynegrid_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    ckLcmType_velodynegrid_t_handler_t f, void *userdata)
{
    ckLcmType_velodynegrid_t_subscription_t *n = (ckLcmType_velodynegrid_t_subscription_t*)
                       malloc(sizeof(ckLcmType_velodynegrid_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 ckLcmType_velodynegrid_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg ckLcmType_velodynegrid_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int ckLcmType_velodynegrid_t_subscription_set_queue_capacity (ckLcmType_velodynegrid_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int ckLcmType_velodynegrid_t_unsubscribe(lcm_t *lcm, ckLcmType_velodynegrid_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe ckLcmType_velodynegrid_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

